import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import Board from '../components/Board';
import { useAppDispatch, useAppSelector } from '../hooks/redux';
import { initializeBoard } from '../redux/slices/boardSlice';

const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  const [isOver, isWon] = useAppSelector(({ board }) => [
    board.isOver,
    board.isWon,
  ]);

  useEffect(() => {
    if (isOver) {
      window.alert('Game over!');
    }
  }, [isOver]);

  useEffect(() => {
    if (isWon) {
      window.alert('You win!');
    }
  }, [isWon]);

  return (
    <div>
      <Head>
        <title>Minesweeper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen flex items-center justify-center flex-col">
        <h1 className="font-extrabold text-3xl sm:text-4xl py-2">
          MINESWEEPER
        </h1>

        <button
          className="my-2 py-2 px-4 bg-gray-200"
          onClick={() => {
            dispatch(initializeBoard());
          }}
        >
          Again
        </button>
        <Board />
      </main>
    </div>
  );
};

export default Home;
