import type { NextPage } from 'next';
import Head from 'next/head';
import Board from '../components/Board';
import { useAppDispatch } from '../hooks/redux';
import { initializeBoard } from '../redux/slices/boardSlice';

const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  return (
    <div>
      <Head>
        <title>Minesweeper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen flex items-center justify-center flex-col">
        <h1 className="font-extrabold text-3xl sm:text-4xl py-2">
          MINESWEEPER
        </h1>

        <Board />

        <button
          className="my-2 py-2 px-4 bg-gray-200"
          onClick={() => {
            dispatch(initializeBoard());
          }}
        >
          Again
        </button>
      </main>
    </div>
  );
};

export default Home;
